# GitLab variables are described here: http://docs.gitlab.com/ce/ci/variables/README.html
# Linter for this file is available here: https://gitlab.com/ci/lint

.template_node_job_configuration: &node_job_configuration
  tags:
    - docker
  image: node:6.10.1-alpine

.template_shell_job_configuration: &shell_job_configuration
  tags:
    - docker
  image: alpine:3.5

.template_aws_deployment_before_script: &aws_deployment_before_script
  before_script:
    - mkdir ${HOME}/.aws
    - touch ${HOME}/.aws/credentials
    - echo "[deployment]" >> ${HOME}/.aws/credentials
    - echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ${HOME}/.aws/credentials
    - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ${HOME}/.aws/credentials
    - yarn install

stages:
  - deploy
  - check-health
  - run-demo

"site:testing:deploy":
  stage: deploy
  only:
    # TODO change to `production` after merge to `master`
    - server
  # TODO change to `testing` after merge to `master`
  environment: "tmp_testing"
  <<: *node_job_configuration
  <<: *aws_deployment_before_script
  script:
    - yarn run deploy-testing

"site:production:deploy":
  when: manual
  stage: deploy
  only:
    # TODO change to `production` after merge to `master`
    - server
  # TODO change to `production` after merge to `master`
  environment: "tmp_production"
  <<: *node_job_configuration
  <<: *aws_deployment_before_script
  script:
    - yarn run deploy-production

"site:testing:health":
  stage: check-health
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job_configuration
  variables:
    API_VERSION: testing
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./check-health.sh

"site:production:health":
  when: manual
  stage: check-health
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job_configuration
  variables:
    API_VERSION: production
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./check-health.sh

"site:testing:demo":
  stage: run-demo
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job_configuration
  variables:
    API_VERSION: testing
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./run-demo.sh

"site:production:demo":
  when: manual
  stage: run-demo
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job_configuration
  variables:
    API_VERSION: production
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./run-demo.sh
