# GitLab variables are described here: http://docs.gitlab.com/ce/ci/variables/README.html
# Linter for this file is available here: https://gitlab.com/ci/lint

.template__node_job__configuration: &node_job__configuration
  tags:
    - docker
  image: node:6.10.1-alpine

.template__shell_job__configuration: &shell_job__configuration
  tags:
    - docker
  image: alpine:3.5

.template__aws_deployment__before_script: &aws_deployment__before_script
  before_script:
    - mkdir ${HOME}/.aws
    - touch ${HOME}/.aws/credentials
    - echo "[deployment]" >> ${HOME}/.aws/credentials
    - echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ${HOME}/.aws/credentials
    - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ${HOME}/.aws/credentials
    - yarn install

stages:
  - test
  - testing-deploy
  - testing-check
  - production-deploy
  - production-check

"test:lint":
  stage: test
  <<: *node_job__configuration
  before_script:
    - yarn install
  script:
    - yarn test

"deploy:testing":
  stage: testing-deploy
  only:
    # TODO change to `production` after merge to `master`
    - server
  # TODO change to `testing` after merge to `master`
  environment: "tmp_testing"
  <<: *node_job__configuration
  <<: *aws_deployment__before_script
  script:
    - yarn run deploy-testing

"deploy:production":
  when: manual
  stage: production-deploy
  only:
    # TODO change to `production` after merge to `master`
    - server
  # TODO change to `production` after merge to `master`
  environment: "tmp_production"
  <<: *node_job__configuration
  <<: *aws_deployment__before_script
  script:
    - yarn run deploy-production

"check:testing":
  stage: testing-check
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job__configuration
  variables:
    API_VERSION: testing
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./check-health.sh

"check:production":
  when: manual
  stage: production-check
  only:
    # TODO change to `production` after merge to `master`
    - server
  <<: *shell_job__configuration
  variables:
    API_VERSION: production
  before_script:
    - apk --update add 'curl=7.52.1-r2' 'jq=1.5-r3'
  script:
    - ./check-health.sh
