# GitLab variables are described here: http://docs.gitlab.com/ce/ci/variables/README.html
# Linter for this file is available here: https://gitlab.com/ci/lint

.template_build_and_test_website: &build_and_test_website
  tags:
    - docker
  image: ruby:2.4.0
  before_script:
    - ./setup.sh
  script:
    - ./build.sh
    - ./test.sh

test:
  stage: test
  except:
    - production
  <<: *build_and_test_website

pages:
  stage: deploy
  only:
    - production
  <<: *build_and_test_website
  artifacts:
    paths:
      - public
