# GitLab variables are described here: http://docs.gitlab.com/ce/ci/variables/README.html
# Linter for this file is available here: https://gitlab.com/ci/lint

# TODO health-check

pages:
  image: node:7.3.0
  only:
    - master
  before_script:
    - npm update
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - public
