<template>
    <section class="content">
        <div v-html="postHtmlContent"></div>
        <embedded-speaker-deck
                v-if="speakerDeckPresentationId"
                :presentation-id="speakerDeckPresentationId"/>
        <embedded-you-tube
                v-if="youtubeVideoUrl"
                :video-url="youtubeVideoUrl"/>
    </section>
</template>

<script>
  import EmbeddedSpeakerDeck from '../EmbeddedSpeakerDeck.vue'
  import EmbeddedYouTube from '../EmbeddedYouTube.vue'

  export default {
    props: {
      postHtmlContent: {type: String, required: true},
      speakerDeckPresentationId: {type: String, required: false},
      youtubeVideoUrl: {type: String, required: false}
    },
    components: {
      EmbeddedSpeakerDeck,
      EmbeddedYouTube
    }
  }

</script>

<!-- TODO make it scoped, modular or whatever… -->
<style lang="less">
    @import "../../assets/styles/theme";

    .content {
        em, strong {
            font-style: normal;
            font-weight: @font__weight__bold;
        }
        a {
            color: @color_font;
            text-decoration: none;
            border: 2px @color_brand;
            border-bottom-style: solid;
        }
        a:hover {
            color: @color_brand;
        }
        blockquote {
            margin-left: 1em;
            padding-left: 1em;
            border: 2px @color_brand;
            border-left-style: solid;
        }
        .post__content__code_inline {
            padding: 0 0.3em;
            border: 1px solid @color_brand;
        }
        .post__content__code {
            padding: 0.3em;
            border: 1px solid @color_brand;
            /* vertical scrollbar */
            overflow: auto;
        }
        .post__content__image {
            border: 1px solid @color_brand;
            max-width: 100%;
            max-height: 600px;

            /* center this element inside parent element */
            margin-left: auto;
            margin-right: auto;
            display: block;
        }
    }
</style>

<style scoped lang="less">
    @import "../../assets/styles/theme";

    .content {
        font-style: normal;
        margin: 0;

        /* TODO better way of defining this media query with 2rems? */
        @media all and (max-width: (800px + 2*@font__size__regular)) {
            margin-left: @page__margin__horizontal;
            margin-right: @page__margin__horizontal;
        }
    }

    /* TODO clean-up */
    /* TODO Class applied in webpack loader. Can we make those styles below not marked as unused? */
    /*noinspection CssUnusedSymbol*/
    .post__content__code {
        /*border: 1px solid #60c17d;*/
        /*border-radius: 3px;*/
        /*padding: 1em;*/
        /*font-size: 0.7em;*/

        /* vertical scrollbar */
        /*overflow: auto;*/
    }

    /* TODO clean-up */
    .post__content__code * {
        /* Are 400 and 700 weights OK? What weights are generated by highlight.js? */
        font-family: @font__code__primary, @font__code__fallback;
    }

    /* TODO clean-up */
    /* TODO Class applied in webpack loader. Can we make those styles below not marked as unused? */
    /*noinspection CssUnusedSymbol*/
    .post__content__code_inline {
        /*border: 1px solid #60c17d;*/
        /*border-radius: 3px;*/
        /*font-size: 0.7em;*/
        /*font-family: monospace;*/

        /* Do not break inline code snippets into lines */
        /*white-space: nowrap;*/
    }

    /* TODO clean-up */
    /* TODO Class applied in webpack loader. Can we make those styles below not marked as unused? */
    /*noinspection CssUnusedSymbol*/
    .post__content__image {
        /* separate images with whit background from white background of the site */
        /*border: 1px solid #60c17d;*/
        /*border-radius: 3px;*/

        max-width: 100%;

        /* do not allow vertical images to take too much space */
        /*max-height: 600px;*/

        /* center this element inside parent element */
        /*display: block;*/
        /*margin-right: auto;*/
        /*margin-left: auto;*/

        /* gap between elements */
        /*noinspection CssOptimizeSimilarProperties*/
        /*margin-top: 1em;*/
        /*noinspection CssOptimizeSimilarProperties*/
        /*margin-bottom: 1em;*/
    }
</style>
